//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;

public class PauseEvent : GameEvent
{
	public bool displayMenu;
	public bool showMouse;

	public PauseEvent ( bool displayMenu, bool showMouse) : base("OnPause")
	{
		this.displayMenu = displayMenu;
		this.showMouse = showMouse;
	}
}


