//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;

public class CookieUtility
{
	public static string cookie { get; set; }
	public static string domain { get; set; }

	public static void RequestCookie()
	{
		Application.ExternalCall ("unityUtil.fetchCookie", "");
	}
}


