////------------------------------------------------------------------------------
//// <auto-generated>
////     This code was generated by a tool.
////     Runtime Version:4.0.30319.18444
////
////     Changes to this file may cause incorrect behavior and will be lost if
////     the code is regenerated.
//// </auto-generated>
////------------------------------------------------------------------------------
//using System;
//using System.IO;
//using System.Runtime.Serialization;
//using System.Runtime.Serialization.Json; // for DataContractJsonSerializer
//
//
//[DataContract]
//public class ServerRequest
//{
//	[DataMember]
//	internal string access = "unity";
//	
//	[DataMember(EmitDefaultValue=false)]
//	internal string expires;
//
//	public ServerRequest(){
//		expires = "" + (int)((System.DateTime.UtcNow - 
//		                     new System.DateTime(1970, 1, 1)).TotalSeconds);
//	}
//
//	public String ToString()
//	{
//		MemoryStream stream1 = new MemoryStream ();
//		DataContractJsonSerializer ser = new DataContractJsonSerializer(typeof(ServerRequest));
//		ser.WriteObject (stream1, this);
//		stream1.Position = 0;
//		StreamReader sr = new StreamReader (stream1);
//		return sr.ReadToEnd();
//	}
//	
//}
//
//
