//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Runtime.Serialization;

[DataContract]
public class GameSave : ServerRequest
{

	[DataMember]
	public int levelsComplete;

	//TODO define what else goes in here

	public GameSave ()
	{

	}
}


