//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.IO;
using System.Runtime.Serialization;

[DataContract]
public class ServerRequest
{
	[DataMember]
	public string access = "unity";
	
	[DataMember(EmitDefaultValue=false)]
	public string expires;

	[DataMember(EmitDefaultValue=false)]
	public string cookie;

	public ServerRequest(){
		expires = "" + (int)((System.DateTime.UtcNow - 
		                     new System.DateTime(1970, 1, 1)).TotalSeconds);
	}

	public ServerRequest( string cookie ) : base() {
		if (cookie != null) {
			this.cookie = cookie;
		}
	}
}


