//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
namespace AssemblyCSharp
{
	public struct Molecule
	{
		public String name; // eg. "Hydrogen Dioxide"
		public String flavorText; // eg. "This molecule is absolutely necessary for life. It is composed of two oxygens and a hydrogen."
		public int numCollected; // eg. "0"
	}
}

