// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------
using System;

	public class StateObj
	{
		private int score;
		private int count;
		private int watercount;
		private int methanecount;

		private float starttime;


		public StateObj ()
		{
		}

		public void SaveState(int score, int count, int watercount, int methanecount, float time){
			this.score = score;
			this.count = count;
			this.watercount = watercount;
			this.methanecount = methanecount;
			this.starttime = time;
		}

		public int getCount(){
			return this.count;
		}
		public int getScore(){
			return this.score;
		}
		public int getWatercount(){
			return this.watercount;
		}
		public int getMethanecount(){
			return this.methanecount;
		}
		public float getStarttime(){
			return this.starttime;
		}

	}


